services:
  openhab:
    image: "openhab/openhab:3.3.0"
    restart: always
    network_mode: host
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./oh_backups/${DT_NAME}/openhab/addons:/openhab/addons"
      - "./oh_backups/${DT_NAME}/openhab/conf:/openhab/conf"
      - "./oh_backups/${DT_NAME}/openhab/userdata:/openhab/userdata"
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Paris"
      USER_ID: "997"
      GROUP_ID: "997"
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0:rwm"