---
- name: "Install OpenHab backup"
  hosts: 159.31.103.193
  # hosts: 192.168.50.20
  # hosts: 159.31.103.193

  tasks:
    - name: "Copy OpenHab backup on Raspberry Pi"
      copy:
        src: ./oh3backup_experimenthaal.back
        dest: /tmp/oh3backup_experimenthaal.back
        owner: pi
        mode: 0644
    - name: "Stop openhab service on Raspberry Pi"
      service:
        name: openhab
        state: stopped
      become: true
    - name: "Install OpenHab backup on Raspberry Pi using CLI"
      ansible.builtin.shell: yes | openhab-cli restore /tmp/oh3backup_experimenthaal.back
      register: openhab_cli_output
      become: true
    - name: "Openhab-CLI output"
      debug:
        msg: "{{ openhab_cli_output.stdout_lines }}"
    - name: "Clean cache openhab"
      ansible.builtin.shell: yes | openhab-cli clean-cache
      register: openhab_cli_output
      become: true
    - name: "Openhab-CLI output"
      debug:
        msg: "{{ openhab_cli_output.stdout_lines }}"
    - name: "Start service openhab"
      service:
        name: openhab
        state: restarted
      become: true
    - name: "Start service motion"
      service:
        name: motion
        state: started
      become: true


#- name: "Restart OpenHab Service"
#  hosts: 159.31.103.193
#  tasks:
#    - name: "Restart service openhab"
#      service:
#        name: openhab
#        state: restarted
#      become: true

